import { useState, useEffect } from 'react';
import { format } from 'date-fns';
import { Bell, Calendar as CalendarIcon, Loader2 } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { recordAudit } from '@/lib/audit';

interface Organization {
  id: string;
  name: string;
  client_code: string;
  broadstreet_advertiser_id?: number | null;
}

interface Site {
  id: string;
  name: string;
  broadstreet_config: Record<string, unknown> | null;
}

interface CreateDisplayCampaignDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess: () => void;
  organizations: Organization[];
  sites: Site[];
  defaultOrgId?: string;
  defaultSiteId?: string;
}

export function CreateDisplayCampaignDialog({
  open,
  onOpenChange,
  onSuccess,
  organizations,
  sites,
  defaultOrgId,
  defaultSiteId
}: CreateDisplayCampaignDialogProps) {
  const [selectedOrgId, setSelectedOrgId] = useState<string>(defaultOrgId || '');
  const [selectedSiteId, setSelectedSiteId] = useState<string>(defaultSiteId || '');
  const [adType, setAdType] = useState<'billboard' | 'skyscraper'>('billboard');
  const [startDate, setStartDate] = useState<Date>(new Date());
  const [endDate, setEndDate] = useState<Date | undefined>();
  const [isInfinite, setIsInfinite] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [notifyClient, setNotifyClient] = useState(true);
  const [customName, setCustomName] = useState('');
  const [hasEditedName, setHasEditedName] = useState(false);

  // Sync local state with props when dialog opens
  useEffect(() => {
    if (open) {
      setSelectedOrgId(defaultOrgId || '');
      setSelectedSiteId(defaultSiteId || '');
      setCustomName('');
      setHasEditedName(false);
    }
  }, [open, defaultOrgId, defaultSiteId]);

  const selectedOrg = organizations.find(o => o.id === selectedOrgId);
  const selectedSite = sites.find(s => s.id === selectedSiteId);

  // Generate campaign name preview
  const autoGeneratedName = selectedOrg && selectedSite
    ? `${selectedOrg.name} (${selectedOrg.client_code}) - ${adType.charAt(0).toUpperCase() + adType.slice(1)} Campaign - ${selectedSite.name}`
    : '';

  // Auto-fill name when org/site/type changes (only if user hasn't manually edited)
  useEffect(() => {
    if (!hasEditedName && autoGeneratedName) {
      setCustomName(autoGeneratedName);
    }
  }, [autoGeneratedName, hasEditedName]);

  const handleSubmit = async () => {
    if (!selectedOrgId || !selectedSiteId) {
      toast({
        title: 'Missing Fields',
        description: 'Please select a client and site',
        variant: 'destructive'
      });
      return;
    }

    setIsSubmitting(true);

    try {
      // Use supabase.functions.invoke to automatically include user's JWT token
      const { data, error } = await supabase.functions.invoke('broadstreet-api', {
        body: {
          action: 'create-campaign',
          organizationId: selectedOrgId,
          siteId: selectedSiteId,
          adType,
          campaignName: customName || autoGeneratedName,
          startDate: format(startDate, 'yyyy-MM-dd'),
          endDate: isInfinite ? null : (endDate ? format(endDate, 'yyyy-MM-dd') : null),
          notifyClient
        }
      });

      if (error) {
        throw new Error(error.message || 'Failed to create campaign');
      }

      if (data?.error) {
        throw new Error(data.error);
      }

      void recordAudit({
        organizationId: selectedOrgId,
        action: 'campaign.created',
        entityType: 'display_ad_campaign',
        entityId: data?.campaign?.id ?? data?.id ?? null,
        summary: `Created display campaign "${customName || autoGeneratedName}" (${adType})`,
        after: {
          name: customName || autoGeneratedName,
          ad_type: adType,
          start_date: format(startDate, 'yyyy-MM-dd'),
          end_date: isInfinite ? null : (endDate ? format(endDate, 'yyyy-MM-dd') : null),
          site_id: selectedSiteId,
        },
        metadata: { notify_client: notifyClient },
      });

      onSuccess();
    } catch (error) {
      console.error('Error creating campaign:', error);
      toast({
        title: 'Error',
        description: error instanceof Error ? error.message : 'Failed to create campaign',
        variant: 'destructive'
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const resetForm = () => {
    setSelectedOrgId(defaultOrgId || '');
    setSelectedSiteId(defaultSiteId || '');
    setAdType('billboard');
    setStartDate(new Date());
    setEndDate(undefined);
    setIsInfinite(true);
    setNotifyClient(true);
    setCustomName('');
    setHasEditedName(false);
  };

  return (
    <Dialog open={open} onOpenChange={(isOpen) => {
      if (!isOpen) resetForm();
      onOpenChange(isOpen);
    }}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>Create Display Ad Campaign</DialogTitle>
          <DialogDescription>
            Create a new display ad campaign in Broadstreet. The advertiser and campaign
            will be automatically created if needed.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* Client Selection */}
          <div className="space-y-2">
            <Label htmlFor="organization">Client</Label>
            <Select value={selectedOrgId} onValueChange={setSelectedOrgId}>
              <SelectTrigger id="organization">
                <SelectValue placeholder="Select a client..." />
              </SelectTrigger>
              <SelectContent>
                {organizations.map(org => (
                  <SelectItem key={org.id} value={org.id}>
                    {org.name} ({org.client_code})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Site Selection */}
          <div className="space-y-2">
            <Label htmlFor="site">Site</Label>
            <Select value={selectedSiteId} onValueChange={setSelectedSiteId}>
              <SelectTrigger id="site">
                <SelectValue placeholder="Select a site..." />
              </SelectTrigger>
              <SelectContent>
                {sites.map(site => (
                  <SelectItem key={site.id} value={site.id}>
                    {site.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {sites.length === 0 && (
              <p className="text-sm text-muted-foreground">
                No sites with Broadstreet enabled. Configure sites in Admin Settings.
              </p>
            )}
          </div>

          {/* Ad Type */}
          <div className="space-y-2">
            <Label htmlFor="adType">Ad Type</Label>
            <Select value={adType} onValueChange={(v) => setAdType(v as 'billboard' | 'skyscraper')}>
              <SelectTrigger id="adType">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="billboard">Billboard (600×300)</SelectItem>
                <SelectItem value="skyscraper">Skyscraper (300×600)</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Start Date */}
          <div className="space-y-2">
            <Label>Start Date</Label>
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className={cn(
                    'w-full justify-start text-left font-normal',
                    !startDate && 'text-muted-foreground'
                  )}
                >
                  <CalendarIcon className="mr-2 h-4 w-4" />
                  {startDate ? format(startDate, 'PPP') : 'Select date...'}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <Calendar
                  mode="single"
                  selected={startDate}
                  onSelect={(date) => date && setStartDate(date)}
                  initialFocus
                />
              </PopoverContent>
            </Popover>
          </div>

          {/* Infinite Toggle */}
          <div className="flex items-center justify-between">
            <Label htmlFor="infinite" className="cursor-pointer">
              Run indefinitely (no end date)
            </Label>
            <Switch
              id="infinite"
              checked={isInfinite}
              onCheckedChange={setIsInfinite}
            />
          </div>

          {/* End Date (if not infinite) */}
          {!isInfinite && (
            <div className="space-y-2">
              <Label>End Date</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    variant="outline"
                    className={cn(
                      'w-full justify-start text-left font-normal',
                      !endDate && 'text-muted-foreground'
                    )}
                  >
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {endDate ? format(endDate, 'PPP') : 'Select end date...'}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={endDate}
                    onSelect={setEndDate}
                    disabled={(date) => date < startDate}
                    initialFocus
                  />
                </PopoverContent>
              </Popover>
            </div>
          )}

          {/* Notify Client Toggle */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Bell className="h-4 w-4 text-muted-foreground" />
              <Label htmlFor="notify" className="cursor-pointer">
                Notify client of new campaign
              </Label>
            </div>
            <Switch
              id="notify"
              checked={notifyClient}
              onCheckedChange={setNotifyClient}
            />
          </div>

          {/* Campaign Name */}
          <div className="space-y-2">
            <Label>Campaign Name</Label>
            <Input
              value={customName}
              onChange={(e) => {
                setCustomName(e.target.value);
                setHasEditedName(true);
              }}
              placeholder={autoGeneratedName || 'Select client and site first...'}
            />
            <p className="text-xs text-muted-foreground">
              Auto-generated from selections — edit if needed
            </p>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={isSubmitting}>
            Cancel
          </Button>
          <Button onClick={handleSubmit} disabled={isSubmitting || !selectedOrgId || !selectedSiteId}>
            {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Create Campaign
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
